version: "3.9"
services:
  evilginx:
    container_name: evilginx2
    image: warhorse/evilginx2:latest     # easiest proven image
    environment:
      TZ: Europe/Copenhagen
    expose:
      - "443"
    labels:
      - coolify.port=443
    volumes:
      - ./config:/config
      - ./phishlets:/phishlets
    stdin_open: true     # <‑‑ keep STDIN open
    tty: true            # <‑‑ allocate a pseudo‑TTY
    restart: unless-stopped

volumes:
  config_data:
  phishlets_data:
