services:
  evilginx:
    build: .
    container_name: evilginx2
    environment:
      TZ: Europe/Copenhagen
    expose:                       # <‑‑ expose, don’t publish
      - "443"
    labels:                       # <‑‑ tell Coolify/Traefik
      - coolify.port=443          # internal port to proxy
    volumes:
      - config_data:/config
      - phishlets_data:/phishlets
    restart: unless-stopped

volumes:
  config_data:
  phishlets_data:
