services:
  evilginx:
    image: warhorse/evilginx2:latest
    container_name: evilginx2        # <‑ optional friendly name
    # Run Evilginx with HTTPS disabled, HTTP on port 80
    command: >
      /bin/evilginx -p /phishlets -c /config
                   -http-port 80
                   -https-port 0
    expose:
      - "80"
    labels:
      - coolify.port=80              # tell Traefik to forward to port 80
    volumes:
      - ./phishlets:/phishlets       # or named volume if you prefer
      - config_data:/config
    restart: unless-stopped
