version: "3.8"

services:
  evilginx:
    image: warhorse/evilginx2:latest
    container_name: evilginx2

    # Completely replace the original entry‑point with an array
    entrypoint:
      - /bin/evilginx
      - -developer
      - -p
      - /phishlets
      - -c
      - /config
      - -http-port
      - "80"
      - -https-port
      - "0"

    expose:
      - "80"

    labels:
      - coolify.port=80                # Traefik forwards plain HTTP

    volumes:
      - ./phishlets:/phishlets         # phishlet YAMLs
      - config_data:/config            # sessions, creds, settings

    restart: unless-stopped

volumes:
  config_data:
